### ISSUE TITLE
have you html code Editor?

### ISSUE THREAD

**Issue by ghost** [mbdavid/Nina#1]
hi @mbdavid  
i working on c# library project for a web site
do you have some library or framework for design html in my c# codes?

something like 
``` 
var html = "<h1> hello </h1>"
```

**Comment by mbdavid** [comment]
Hi @miladsadeghi72, did you try https://www.tinymce.com ? It's very useful/advanced/free editor.... (there is a community edition)

**Comment by ghost** [comment]
thanks
