### ISSUE TITLE
convert bytes to image without Data URL

### ISSUE THREAD

**Issue by ghost** [mbdavid/Nina#2]
hi david
i working on new my http service
this project is for all devices and run via C# and some web browser
this is something like Cordova, this can be a web site, or an app

how ever, now i have a little problem with Data Conversions
when i send response to browser, i must send image directly
so i use Data URL as conversion
the problem is base64 convert is act very long time and also some of browsers limit length of Data URL

if dont understand what i say :

[Data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs)

do you know any else solution for that?

**Comment by mbdavid** [comment]
Hi, 

If you have large images to serve, do not use base64 image types. Try write a specific http handler to handle this file. You can use some like:

`<img src="img-handler/<image-guid>" />`

And than write controller to handle this `img-handler` path with Id image. In this controller, return image mime-type + byte array on response body.

**Comment by ghost** [comment]
tnx bro but i dont using page routing like asp.net
my http server have different routing for every requests
my problem solved via some inner request like ajax
however thank you for response

my problem was when i take picture in mobile app then i need to show that for user
so i have two way to do that, save picture or send picture as Data URL
i send picture, but i dont use Data URL
