### ISSUE TITLE
i have same other, what is benefit if ...

### ISSUE THREAD

**Issue by ghost** [mbdavid/Nina#3]
hi @mbdavid and wishing you success

i make a new framework for HTTP service, that is awesome and very simple
that have different logic compare to Microsoft MVC and simpler of that 
that is something like asp core and can use in any platforms
now i have a question
if i share it on GitHub then what is benefits for me?
you must know we are in Iran and sanctioned 
what is your opinion?

**Comment by mbdavid** [comment]
Hi @miladsadeghi72, if want that your project be an open source project, github is best place for that. There a big community here that can help and contribute to your project. And now, after microsoft buys github, I think this will better, more integrate with microsoft tools.

**Comment by ghost** [comment]
thanks, i got that

**Comment by ghost** [comment]
https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:6452178773583499264

its that.

**Comment by ghost** [comment]
hi @mbdavid and wish best for you
this is what i talking about
https://github.com/miladsadeghi72/Monsajem_WebsiteService
